# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, tsssni-pkgs, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    loader = {
      grub = {
        enable = true;
        zfsSupport = true;
        efiSupport = true;
        useOSProber = true;
        mirroredBoots = [
          {
            devices = [ "nodev" ];
            path = "/efi";
          }
        ];
        theme = tsssni-pkgs.tsssni-grub-theme;
        configurationLimit = 5;
      };
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/efi";
      };
    };
  };

  fileSystems = {
    "/" = { 
      device = "zpool";
      fsType = "zfs";
    };

    "/efi" = { 
      device = "/dev/disk/by-uuid/4757-51E1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  };

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
