local palette = require('plana.palette')
local lush = require('lush')
vim.g.terminal_color_0 = palette.black
vim.g.terminal_color_8 = palette.light_black
vim.g.terminal_color_1 = palette.red
vim.g.terminal_color_9 = palette.light_red
vim.g.terminal_color_2 = palette.green
vim.g.terminal_color_10 = palette.light_green
vim.g.terminal_color_3 = palette.yellow
vim.g.terminal_color_11 = palette.light_yellow
vim.g.terminal_color_4 = palette.blue
vim.g.terminal_color_12 = palette.light_blue
vim.g.terminal_color_5 = palette.magenta
vim.g.terminal_color_13 = palette.light_magenta
vim.g.terminal_color_6 = palette.cyan
vim.g.terminal_color_14 = palette.light_cyan
vim.g.terminal_color_7 = palette.white
vim.g.terminal_color_15 = palette.light_white
---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    ColorColumn { fg = palette.black, bg = palette.red },
    Conceal { fg = palette.light_black },
    Cursor { fg = palette.blue },
    CurSearch { fg = palette.black, bg = palette.light_magenta },
    lCursor { fg = palette.white },
    CursorIM { fg = palette.white },
    CursorColumn { bg = palette.back },
    CursorLine { bg = palette.back },
    CursorLineNr { fg = palette.light_magenta },
    LineNr { fg = palette.magenta },
    Directory { fg = palette.red },
    DiffAdd { fg = palette.light_green },
    DiffChange { fg = palette.light_yellow },
    DiffDelete { fg = palette.red },
    DiffText { fg = palette.light_blue },
    GitSignsAdd { fg = palette.light_green },
    GitSignsChange { fg = palette.light_yellow },
    GitSignsDelete { fg = palette.red },
    Added { fg = palette.light_green },
    Changed { fg = palette.light_yellow },
    Removed { fg = palette.red },
    EndOfBuffer { fg = palette.blue },
    TermCursor { fg = palette.black, bg = palette.light_black },
    TermCursorNC { fg = palette.light_black },
    ErrorMsg { fg = palette.black, bg = palette.red },
    VertSplit { fg = palette.black },
    Folded { fg = palette.light_blue },
    FoldColumn { fg = palette.light_blue },
    SignColumn { fg = palette.red, bg = palette.back },
    IncSearch { fg = palette.black, bg = palette.light_magenta },
    Substitute { fg = palette.black, bg = palette.light_magenta },
    MatchParen { fg = palette.yellow },
    NonText { fg = palette.light_black },
    Normal { fg = palette.front, bg = palette.back },
    NormalFloat { fg = palette.front, bg = palette.back },
    Pmenu { fg = palette.light_white, bg = palette.back },
    PmenuSel { bg = palette.light_black },
    PmenuSbar { fg = palette.light_black, bg = palette.black },
    PmenuThumb { fg = palette.black, bg = palette.light_black },
    Question { fg = palette.green },
    QuickFixLine { fg = palette.black, bg = palette.light_magenta },
    Search { fg = palette.black, bg = palette.light_magenta },
    SpecialKey { fg = palette.cyan },
    SpellBad { fg = palette.white, sp = palette.red, undercurl = true },
    SpellCap { fg = palette.white, sp = palette.blue, undercurl = true },
    SpellLocal { fg = palette.white, sp = palette.cyan, undercurl = true },
    SpellRare { fg = palette.white, sp = palette.magenta, undercurl = true },
    StatusLine { fg = palette.light_white, bg = palette.back },
    StatusLineNC { fg = palette.white, bg = palette.back },
    SnippetTabstop { },
    Title { fg = palette.red },
    Visual { bg = palette.light_black },
    VisualNOS { fg = palette.black },
    WarningMsg { fg = palette.red },
    Whitespace { fg = palette.light_black },
    Winseparator { fg = palette.black },
    WildMenu { fg = palette.light_green },
    WinBar { fg = palette.light_black },
    WinBarNC { fg = palette.light_black },
    Comment { fg = palette.white },
    Constant { fg = palette.light_green },
    String { fg = palette.green },
    Character { fg = palette.green },
    Identifier { fg = palette.cyan },
    Function { fg = palette.blue },
    Statement { fg = palette.green },
    Operator { fg = palette.light_white },
    PreProc { fg = palette.blue },
    Type { fg = palette.red },
    Special { fg = palette.light_blue },
    Delimiter { fg = palette.light_blue },
    Underlined { gui = 'underline', fg = palette.magenta },
    Ignore { fg = palette.light_black },
    Error { fg = palette.black, bg = palette.red },
    Todo { fg = palette.black, bg = palette.light_yellow },
    DiagnosticError { fg = palette.red },
    DiagnosticWarn { fg = palette.yellow },
    DiagnosticInfo { fg = palette.blue },
    DiagnosticHint { fg = palette.cyan },
    DiagnosticOk { fg = palette.light_green },
    BlinkCmpKind { fg = palette.front },
    BlinkCmpKindFunction { fg = palette.blue },
    BlinkCmpKindMethod { fg = palette.blue },
    BlinkCmpKindConstructor { fg = palette.blue },
    BlinkCmpKindVariable { fg = palette.light_white },
    BlinkCmpKindField { fg = palette.cyan },
    BlinkCmpKindProperty { fg = palette.cyan },
    BlinkCmpKindClass { fg = palette.red },
    BlinkCmpKindInterface { fg = palette.red },
    BlinkCmpKindStruct { fg = palette.red },
    BlinkCmpKindModule { fg = palette.light_white },
    BlinkCmpKindEnum { fg = palette.red },
    BlinkCmpKindEnumMember { fg = palette.light_green },
    BlinkCmpKindKeyword { fg = palette.green },
    BlinkCmpKindConstant { fg = palette.light_green },
    BlinkCmpKindSnippet { fg = palette.light_magenta },
    BlinkCmpKindText { fg = palette.white },
    BlinkCmpKindValue { fg = palette.light_green },
    BlinkCmpKindUnit { fg = palette.light_green },
    BlinkCmpKindColor { fg = palette.yellow },
    BlinkCmpKindFile { fg = palette.light_red },
    BlinkCmpKindFolder { fg = palette.light_red },
    BlinkCmpKindReference { fg = palette.magenta },
    BlinkCmpKindEvent { fg = palette.yellow },
    BlinkCmpKindOperator { fg = palette.green },
    BlinkCmpKindTypeParameter { fg = palette.red },
    BlinkPairsOrange { fg = palette.light_red },
    BlinkPairsPurple { fg = palette.magenta },
    BlinkPairsBlue { fg = palette.blue },
    BlinkPairsUnmatched { fg = palette.black, bg = palette.red },
    BlinkPairsMatchParen { fg = palette.yellow },
    Headline { fg = palette.red, bold = true },
    Headline1 { fg = palette.red, bold = true },
    Headline2 { fg = palette.light_green, bold = true },
    Headline3 { fg = palette.light_yellow, bold = true },
    Headline4 { fg = palette.light_blue, bold = true },
    Headline5 { fg = palette.light_magenta, bold = true },
    sym'@variable' { fg = palette.light_white },
    sym'@markup.heading.1.markdown' { fg = palette.red, bold = true },
    sym'@markup.heading.2.markdown' { fg = palette.light_green, bold = true },
    sym'@markup.heading.3.markdown' { fg = palette.light_yellow, bold = true },
    sym'@markup.heading.4.markdown' { fg = palette.light_blue, bold = true },
    sym'@markup.heading.5.markdown' { fg = palette.light_magenta, bold = true },
}
end)
return theme

